

<?php
 // module/User/view/user/user/add.phtml:

 $title = 'Add new user';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('user', array('action' => 'add')));
 $form->setAttribute('class', 'form-horizontal');
 $form->prepare();

 echo $this->form()->openTag($form);
 ?>
<div class="container"> 
 <?php echo $this->formHidden($form->get('id')); ?>
    <div class="form-group">
        <label for="exampleInputFile" class ="col-sm-2 control-label">User Name</label>
        <div class="col-sm-2"><?php echo $this->formRow($form->get('username'));?></div>
    </div>
    <div class="form-group">
        <label for="exampleInputFile" class ="col-sm-2 control-label">First Name</label>
        <div class="col-sm-2"><?php echo $this->formRow($form->get('firstname'));?></div>
    </div>
    <div class="form-group">
        <label for="exampleInputFile" class ="col-sm-2 control-label">Last Name</label>
        <div class="col-sm-2"><?php echo $this->formRow($form->get('lastname'));?></div>
    </div>
    <div class="form-group">
        <label for="exampleInputFile" class ="col-sm-2 control-label">Email</label>
        <div class="col-sm-2"><?php echo $this->formRow($form->get('email'));?></div>
    </div>
    <div class="form-group">
        <label for="exampleInputFile" class ="col-sm-2 control-label">Phone</label>
        <div class="col-sm-2"><?php echo $this->formRow($form->get('phone'));?></div>
    </div>
    <div class="form-group">
       <div class="col-sm-offset-2 col-sm-10"><?php echo $this->formRow($form->get('submit')); ?></div>
    </div>
 <?php echo $this->form()->closeTag(); ?>
 </div>